import{i as l}from"./assets/vendor-38388549.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const f="42782608-9283e0435a58714aa19763cda",d="https://pixabay.com/api/";function m(r,t){const s=new URLSearchParams({key:f,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:20}),n=`${d}/?${s}`;return fetch(n).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()})}m("tree",1).then(r=>console.log(r.hits)).catch(r=>console.log(r.message));function p(r){return r.map(({webformatURL:t,tags:s})=>` <li class="gallery-item data-tilt" > 
              <a class="gallery-link" href="${t}">
              <img
                class="gallery-image"
                src="${t}"
                alt="${s}"
              />
            </a>
          </li>`).join("")}const u={message:"Sorry, there are no images matching  your search query. Please, try again!",messageSize:"16",messageLineHeight:"24",iconUrl:"./img/error.svg",backgroundColor:"rgb(239, 64, 64)",messageColor:"rgb(255, 255, 255)",titleColor:"rgb(255, 255, 255)",position:"topRight",close:"rgb(255, 255, 255)",maxWidth:"432px"},h=document.querySelector(".js-search-form"),g=document.querySelector(".js-gallery"),i=h.querySelector(".js-input");let c,y=1;h.addEventListener("submit",b);function b(r){if(r.preventDefault(),g.innerHTML="",c=r.currentTarget.elements["user-search-q"].value.trim(),!c)return l.error(u);m(c,y).then(t=>{if(t.hits.length===0){l.error(u);return}alert(`We found ${t.total} photos`),g.innerHTML=p(t.hits)}).catch(console.log),r.currentTarget.reset()}i.addEventListener("focus",()=>{i.removeAttribute("placeholder")});i.addEventListener("blur",()=>{i.setAttribute("placeholder","Search images...")});
//# sourceMappingURL=commonHelpers.js.map
